server.port=8099
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.secret=transpolink-secret-key-must-be-at-least-256-bits-long

spring.cloud.gateway.routes[0].id=identity-service
spring.cloud.gateway.routes[0].uri=lb://identity-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**
spring.cloud.gateway.routes[0].filters[0]=JwtAuthFilter

spring.cloud.gateway.routes[1].id=incident-service
spring.cloud.gateway.routes[1].uri=lb://incident-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/incidents/**,/api/resolutions/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthFilter

spring.cloud.gateway.routes[2].id=traffic-service
spring.cloud.gateway.routes[2].uri=lb://traffic-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/road-segments/**,/api/traffic-flows/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthFilter

spring.cloud.gateway.routes[3].id=transport-service
spring.cloud.gateway.routes[3].uri=lb://transport-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/routes/**,/api/schedules/**,/api/fleets/**
spring.cloud.gateway.routes[3].filters[0]=JwtAuthFilter

spring.cloud.gateway.routes[4].id=compliance-service
spring.cloud.gateway.routes[4].uri=lb://compliance-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/compliance/**,/api/audits/**
spring.cloud.gateway.routes[4].filters[0]=JwtAuthFilter

spring.cloud.gateway.routes[5].id=reporting-service
spring.cloud.gateway.routes[5].uri=lb://reporting-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/reports/**
spring.cloud.gateway.routes[5].filters[0]=JwtAuthFilter

spring.cloud.gateway.routes[6].id=notification-service
spring.cloud.gateway.routes[6].uri=lb://notification-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/notifications/**
spring.cloud.gateway.routes[6].filters[0]=JwtAuthFilter
